on:
  workflow_dispatch:
    inputs:
      ARCH_BASE_SEED:
        description: "seed"
        required: true
        default: "production"
  push:
     branches:
      - main
 
jobs:
  deploy_to_aeHosting:
    runs-on: ubuntu-latest
    name: A job to deploy file to aeHosting
    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Deploy to aeHosting
          id: deploy
          uses: archethic-foundation/aeweb-github-action@v1.8.10
          with:
            seed: ${{  github.event.inputs.ARCH_BASE_SEED }}
            endpoint: "https://testnet.archethic.net"
            path: "/"
            sendTransactionTimeout: 260
            percentageOfConfirmations: 50
        - name: Show URL
          run: echo "URL = ${{ steps.deploy.outputs.website_url }}"
