on:
  workflow_dispatch:
    inputs:
      ARCH_BASE_SEED:
        description: "seed"
        required: true
        default: "production"
  push:
    branches:
      - main

jobs:
  deploy_to_aeHosting:
    runs-on: ubuntu-latest
    name: A job to deploy file to aeHosting
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to aeHosting
        id: deploy  # ✅ Ce ID est essentiel pour `steps.deploy.outputs.*`
        uses: archethic-foundation/aeweb-github-action@v1.8.15
        with:
          seed: ${{ github.event.inputs.ARCH_BASE_SEED }}
          endpoint: "https://testnet.archethic.net"
          path: "/"
          sendTransactionTimeout: 260
          percentageOfConfirmations: 50

      - name: Dump all GitHub context
        run: echo "$GITHUB_OUTPUT"
        env:
          GITHUB_OUTPUT: $GITHUB_OUTPUT
 
      - name: Show URL
        run: echo "URLTA = ${{ steps.deploy.outputs.transaction-address }}"

      - name: Show URL
        run: echo "URL = ${{ steps.deploy.outputs.website_url }}"
        
      - name: Notify deployment
        run: |
           curl -X POST https://ae-deploy-button.vercel.app/api/webhook \
           -H "Content-Type: application/json" \
           -d '{"runId": "${{ github.run_id }}", "address": "${{ steps.deploy.outputs.website_url }}"}'

        
    outputs:
       website_url: ${{ steps.deploy.outputs.website_url }}
